AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Alias:
    Description: The prefix for the DynamoDB tables
    Type: AWS::SSM::Parameter::Value<String>
  BucketName:
    Description: The name of the S3 bucket
    Type: String

Resources:
  StoreTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub "${Alias}_Store"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  UserTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub "${Alias}_Users"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ContractsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub "${Alias}_Contracts"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName